platform:
  - x64
version: 1.0.{build}
branches:
  only:
    - master
install:
  - ps: Install-Product node 6 x64
before_build:
  - npm install --only=dev
  - npm run postinstall
  - npm run lint
build_script:
  - npm run build-win
