platform:
  - x64
version: 1.0.{build}
branches:
  only:
    - master
install:
  - ps: Install-Product node 6 x64
clone_script:
  - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
before_build:
  - npm install --only=dev
  - npm run postinstall
  - npm run lint
build_script:
  - npm run build-win
